### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by zhaoyuanmeng** [yaogengzhu/webpack#1]
我看第15节课的时候 打包那个react 报错

**Comment by zhaoyuanmeng** [comment]
![image](https://user-images.githubusercontent.com/43205695/172796919-566715f5-5ae5-447d-98b0-af75de731142.png)

**Comment by zhaoyuanmeng** [comment]
查询了一下 没解决。。

**Comment by yaogengzhu** [comment]
提示你需要合适的loader解决！ 可以参考下webpack.config.js 配置看下，具体是 否配置了 合适的loader 以及babel 配置！
```js
 { test: /\.(js|jsx)$/, use: 'babel-loader' },
```

**Comment by zhaoyuanmeng** [comment]
这问题就很神奇 我重新又写了一份 就没问题了又。。
